#!/bin/sh
prev_head=$1
new_head=$2
checkout_type=$3

# 1 = checkout de rama, 0 = checkout de archivo
if [ "$checkout_type" != "1" ]; then
  exit 0
fi

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(main|dev|feature/[a-zA-Z0-9\-]+)$"

if [ "$local_branch" = "HEAD" ]; then
    exit 0
fi

if ! echo "$local_branch" | grep -Eq "$valid_branch_regex"; then
    echo "🛑 [ERROR DevOps] Nomenclatura de rama o creacion invalida: '$local_branch'"
    echo "Revirtiendo accion por violacion de reglas de nombramiento..."
    
    # Forzar el regreso a la rama en la que estaba el usuario
    git checkout -qf - 
    
    # Borrar la rama invalida (force delete dadas las restricciones)
    git branch -D $local_branch >/dev/null 2>&1
    
    echo "❌ Rama '$local_branch' destruida automáticamente."
    echo "💡 Usa uno de los formatos permitidos (ej. git checkout -b feature/mi-tarea)"
fi

exit 0
