version: '3.8'

services:
  brainsort-db:
    image: postgres:15-alpine
    container_name: brainsort_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-brainsort}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-brainsort_password}
      POSTGRES_DB: ${DB_NAME:-brainsort_db}
    ports:
      - '5432:5432'
    volumes:
      - brainsort_pgdata:/var/lib/postgresql/data

volumes:
  brainsort_pgdata:
